### ISSUE TITLE
NuclearCraft

### ISSUE THREAD

**Issue by Ristellise** [Forecaster/RailcraftPatronServerIssues#25]
https://minecraft.curseforge.com/projects/nuclearcraft-mod

MOAR EU

on a more serious not.. it is up to you if you wanna include it. it supports EU as of 1.10 versions

**Comment by liach** [comment]
personally I don't like that, looks like a RF mod

**Comment by hanakocz** [comment]
We would not have ores for that. Also yes, it is mainly RF mod, both in usage, wiki (well all the wiki has are fuels and RF they produce...), and also probably even code-wise. ~~And it looks like it has no explosions.~~ By issues on github it should rather crash the server instead of explosion...yay...
No radioactivity, poor compability with IC2 except EU/HU outputs (according to github issues that ask for more of it)

If we want some extension around nuclear reactors, I would vote for Nuclear control - or for 1.10 it is renamed to World Control https://minecraft.curseforge.com/projects/world-control , even though that is also heavily WIP yet.

**Comment by Forecaster** [comment]
This has too much overlap with ic2 in my opinion. We've got nuclear power already. I know if also has fusion reactors and stuff but no.
